imports:
    -
        resource: ezpublish.yml

doctrine:
    dbal:
        connections:
            ezdeploy_repository_connection:
                driver: pdo_mysql
                host: mysql
                user: user_ezdeploy
                password: NotSoSecret
                dbname: ezdeploy
                charset: UTF8

stash:
    caches:
        default:
            drivers: [ Memcache ]
            inMemory: true
            registerDoctrineAdapter: false
            Memcache:
                prefix_key: ezdeploy_
                retry_timeout: 1
                servers:
                    -
                        server: memcached
                        port: 11211
